config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("curriculums/", include("curriculums.urls", namespace="curriculums")),
    path("users/", include("users.urls", namespace="users")),
    path("book_clubs/", include("book_clubs.urls", namespace="book_clubs")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt",
                                             content_type='text/plain')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from curriculums import views as curriculum_views

app_name = "core"

urlpatterns = [path("", curriculum_views.HomeView.as_view(), name="home")]

curriculums/urls.py
from django.urls import path

from . import views

app_name = "curriculums"

urlpatterns = [
    path("<int:pk>", views.CurriculumDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("category/lifestyle", views.LifestyleView.as_view(), name="lifestyle"),
    path("category/travel", views.TravelView.as_view(), name="travel"),
    path("category/knowledge", views.KnowledgeView.as_view(), name="knowledge"),
    path("category/fiction", views.FictionView.as_view(), name="fiction"),
    path("nav/", views.NavView.as_view(), name="nav"),
    path("application/", views.post, name="application"),

]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500 flex flex-col">
    <span>
        Please don't copy us.
    </span>
    <span>&copy; 2020 Curribook. All rights reserved.</span>
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
        {% for message in messages %}
            <li class="message font-medium bg-gray-700 z-10 rounded-full text-white py-4 px-6 w-64 text-center
                    {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
{% extends "base.html" %}

{% block page_title %}
    커리북 | 내게 맞는 책, 지금 필요한 독서
{% endblock page_title %}

{% block content %}
    <div class="px-5">
        <div class="container border-b border-black mt-20 pb-6 mx-auto xl:max-w-full mb-4">
            <span class="font-extrabold text-sm mb-12 border border-black p-1">카</span>
            <span class="font-extrabold text-sm mb-12 border-t border-r border-b border-black p-1 -mx-1">테</span>
            <span class="font-extrabold text-sm mb-12 border-t border-r border-b border-black p-1 ">고</span>
            <span class="font-extrabold text-sm mb-12 border-t border-r border-b border-black p-1 -mx-1">리</span>
        </div>
        <div class="flex">
            <div class="mr-20">
                <ul>
                    <a href="{% url "curriculums:lifestyle" %}">
                        <li class="text-sm mb-2">라이프스타일</li>
                    </a>
                    <a href="{% url "curriculums:knowledge" %}">
                        <li class="text-sm">지식</li>
                    </a>
                </ul>
            </div>
            <div>
                <ul>
                    <a href="{% url "curriculums:travel" %}">
                        <li class="text-sm mb-2">여행</li>
                    </a>
                    <a href="{% url "curriculums:fiction" %}">
                        <li class="text-sm">소설</li>
                    </a>
                </ul>
            </div>
        </div>
        <div class="container border-b border-black mt-10 pb-6 mx-auto xl:max-w-full mb-4">
            <span class="font-extrabold text-sm mb-12 border border-black p-1">더</span>
            <span class="font-extrabold text-sm mb-12 border-t border-r border-b border-black p-1 -mx-1">보</span>
            <span class="font-extrabold text-sm mb-12 border-t border-r border-b border-black p-1 ">기</span>
        </div>
        <div class="flex mb-10">
            <div class="mr-20">
                <ul>
                    <a href="https://www.instagram.com/baeksoo_seojum/">
                        <li class="text-sm mb-2">인스타그램</li>
                    </a>
                    <a href="http://pf.kakao.com/_lxkJxkj">
                        <li class="text-sm mb-2">문의</li>
                    </a>
                </ul>
            </div>
            <div>
                <ul>
                    <a href="{% url "curriculums:application" %}">
                        <li class="text-sm mb-2">크리에이터 지원</li>
                    </a>

                </ul>
            </div>
        </div>
    </div>

{% endblock content %}