book_clubs/urls.py
from django.urls import path

from . import views

app_name = "book_clubs"

urlpatterns = [
    path("", views.BookReviewView.as_view(), name="review"),
    path("<int:pk>", views.BookReviewDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditBookReviewView.as_view(), name="edit"),
    path("list/", views.BookClubListView.as_view(), name="home"),
    path("list/england", views.EnglandView.as_view(), name="england"),
    path("list/dog", views.DogView.as_view(), name="dog"),
    path("list/consumer", views.ConsumerView.as_view(), name="consumer"),
    path("list/think", views.ThinkView.as_view(), name="think"),
    path("create/", views.CreateBookReviewView.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("curriculums/", include("curriculums.urls", namespace="curriculums")),
    path("users/", include("users.urls", namespace="users")),
    path("book_clubs/", include("book_clubs.urls", namespace="book_clubs")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt",
                                             content_type='text/plain')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from curriculums import views as curriculum_views

app_name = "core"

urlpatterns = [path("", curriculum_views.HomeView.as_view(), name="home")]

templates/mixins/banner.html
<div class="max-w-full lg:px-20">
    <a href="{% url "curriculums:detail" banner.pk %}"
       class="transition duration-500 ease-in-out hover:text-indigo-500">
        <div class="flex flex-col lg:flex-row items-center justify-center">
            <div class="w-auto h-auto bg-cover bg-center mb-4 lg:mr-40 ">
                <img src="{{ banner.cover_photo }}">
            </div>
            <div class="px-5">
                <div class="text-center">
                    <div class="inline-block text-sm text-gray-500 mb-5 border-b-2">
                        {{ banner.category }}
                    </div>
                </div>
                <div class="text-3xl md:text-4xl lg:text-4xl font-extrabold mb-3 text-center">
                    {{ banner.title }}
                </div>
                <div class="text-base md:text-lg font-light text-gray-600 mb-4 text-center">
                    {{ banner.sub_title }}
                </div>
            </div>
        </div>
    </a>
</div>

templates/mixins/bookReview_card.html
<div class="mx-auto mb-10 px-3 py-5 w-11/12 lg:w-8/12 shadow-md ">
    <a href="{% url 'book_clubs:detail' BookReviews.pk %}">
        <div class="text-base font-bold mb-3">
            {{ BookReviews.title | truncatechars:24 }}
        </div>
        <div class="text-sm font-light mb-3">
            {{ BookReviews.description | safe | truncatechars:52 }}
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ BookReviews.category_BookReview }}
            </div>
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ BookReviews.created | date:"Y.m.d" }}
            </div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                by {{ BookReviews.author.name }}
            </div>
        </div>
    </a>
</div>

templates/mixins/bookReview_card_consumer.html
<div class="mx-auto mb-10 px-3 py-5 w-11/12 lg:w-1/2 shadow-md ">
    <a href="{% url 'book_clubs:detail' consumer.pk %}">
        <div class="text-base font-bold mb-3">
            {{ consumer.title | truncatechars:24 }}
        </div>
        <div class="text-sm font-light mb-3">
            {{ consumer.description | truncatechars:52 }}
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ consumer.category_BookReview }}
            </div>
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ consumer.created | date:"Y.m.d" }}
            </div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                by {{ consumer.author.name }}
            </div>
        </div>
    </a>
</div>

templates/mixins/bookReview_card_dog.html
<div class="mx-auto mb-10 px-3 py-5 w-11/12 lg:w-1/2 shadow-md ">
    <a href="{% url 'book_clubs:detail' dog.pk %}">
        <div class="text-base font-bold mb-3">
            {{ dog.title | truncatechars:24 }}
        </div>
        <div class="text-sm font-light mb-3">
            {{ dog.description | truncatechars:52 | safe }}
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ dog.category_BookReview }}
            </div>
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ dog.created | date:"Y.m.d" }}
            </div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                by {{ dog.author.name }}
            </div>
        </div>
    </a>
</div>

templates/mixins/bookReview_card_england.html
<div class="mx-auto mb-10 px-3 py-5 w-11/12 lg:w-1/2 shadow-md ">
    <a href="{% url 'book_clubs:detail' england.pk %}">
        <div class="text-base font-bold mb-3">
            {{ england.title | truncatechars:24 }}
        </div>
        <div class="text-sm font-light mb-3">
            {{ england.description | truncatechars:52 }}
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ england.category_BookReview }}
            </div>
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ england.created | date:"Y.m.d" }}
            </div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                by {{ england.author.name }}
            </div>
        </div>
    </a>
</div>

templates/mixins/bookReview_card_think.html
<div class="mx-auto mb-10 px-3 py-5 w-11/12 lg:w-1/2 shadow-md ">
    <a href="{% url 'book_clubs:detail' think.pk %}">
        <div class="text-base font-bold mb-3">
            {{ think.title | truncatechars:24 }}
        </div>
        <div class="text-sm font-light mb-3">
            {{ think.description | truncatechars:52 }}
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ think.category_BookReview }}
            </div>
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ think.created | date:"Y.m.d" }}
            </div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                by {{ think.author.name }}
            </div>
        </div>
    </a>
</div>

templates/mixins/bookReview_card_user.html
<div class="mx-auto mb-10 px-3 py-5 w-11/12 shadow-md ">
    <a href="{% url 'book_clubs:detail' bookreview.pk %}">
        <div class="text-base font-bold mb-3">
            {{ bookreview.title | truncatechars:24 }}
        </div>
        <div class="text-sm font-light mb-3">
            {{ bookreview.description | truncatechars:52 }}
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ bookreview.category_BookReview }}
            </div>
        </div>
        <div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                {{ bookreview.created | date:"Y.m.d" }}
            </div>
            <div class="inline-block text-xs text-gray-500 font-normal">
                by {{ bookreview.author.name }}
            </div>
        </div>
    </a>
</div>

templates/mixins/curriculum_card.html
<div class="w-1/4 mb-10 px-3">
    <a href="{% url 'curriculums:detail' curriculum.pk %}">
        <div class="w-full h-80 bg-cover bg-center mb-4 "
             style="background-image: url({{ curriculum.cover_photo }});">
        </div>
        <div class="text-center">
            <div class="inline-block text-sm text-gray-500 mb-8 border-b-2">
                {{ curriculum.category }}
            </div>
        </div>

        <div class="text-base font-bold mb-3 text-center">
            {{ curriculum.title }}
        </div>
        <div class="text-sm font-normal text-gray-700 mb-4 text-center">
            {{ curriculum.sub_title }}
        </div>
    </a>
</div>

templates/mixins/curriculum_card_3.html
<div class="w-full lg:w-1/3 mb-20 md:mb-24 px-3 md:px-16 lg:px-10">
    <a href="{% url 'curriculums:detail' recommendation.pk %}">
        <div class="w-auto h-auto bg-cover bg-center mb-4  ">
            <img src="{{ recommendation.cover_photo }}">
        </div>
        <div class="text-center">
            <div class="inline-block text-sm lg:text-sm text-gray-500 mb-4 sm:mb-8 border-b-2">
                {{ recommendation.category }}
            </div>
        </div>
        <div class="text-2xl md:text-3xl lg:text-2xl font-bold mb-2 text-center">
            {{ recommendation.title }}
        </div>
        <div class="font-normal md:text-lg text-gray-600 mb-4 text-center">
            {{ recommendation.sub_title }}
        </div>
    </a>
</div>

templates/mixins/curriculum_card_5_fiction.html
<div class="w-full sm:w-1/5 mb-10 px-4">
    <a href="{% url 'curriculums:detail' fiction.pk %}">
        <div class="w-full h-72 bg-cover bg-center mb-4 "
             style="background-image: url({{ fiction.cover_photo }});">
        </div>
        <div class="text-center">
            <div class="inline-block text-sm text-gray-500 mb-8 border-b-2">
                {{ fiction.category }}
            </div>
        </div>

        <div class="text-lg font-bold mb-3 text-center">
            {{ fiction.title }}
        </div>
        <div class="text-sm font-normal text-gray-700 mb-4 text-center">
            {{ fiction.sub_title }}
        </div>
    </a>
</div>

templates/mixins/curriculum_card_5_knowledge.html
<div class="w-full sm:w-1/5 mb-10 px-4">
    <a href="{% url 'curriculums:detail' knowledge.pk %}">
        <div class="w-full h-72 bg-cover bg-center mb-4 "
             style="background-image: url({{ knowledge.cover_photo }});">
        </div>
        <div class="text-center">
            <div class="inline-block text-sm text-gray-500 mb-8 border-b-2">
                {{ knowledge.category }}
            </div>
        </div>

        <div class="text-lg font-bold mb-3 text-center">
            {{ knowledge.title }}
        </div>
        <div class="text-sm font-normal text-gray-700 mb-4 text-center">
            {{ knowledge.sub_title }}
        </div>
    </a>
</div>

templates/mixins/curriculum_card_5_lifestyle.html
<div class="w-full sm:w-1/5 mb-10 px-4">
    <a href="{% url 'curriculums:detail' lifestyle.pk %}">
        <div class="w-full h-72 bg-cover bg-center mb-4 "
             style="background-image: url({{ lifestyle.cover_photo }});">
        </div>
        <div class="text-center">
            <div class="inline-block text-sm text-gray-500 mb-8 border-b-2">
                {{ lifestyle.category }}
            </div>
        </div>

        <div class="text-lg font-bold mb-3 text-center">
            {{ lifestyle.title }}
        </div>
        <div class="text-sm font-normal text-gray-700 mb-4 text-center">
            {{ lifestyle.sub_title }}
        </div>
    </a>
</div>

templates/mixins/curriculum_card_5_popular.html
<div class="w-full sm:w-1/5 mb-10 px-4">
    <a href="{% url 'curriculums:detail' popular.pk %}">
        <div class="w-auto h-auto bg-cover bg-center mb-4">
            <img src="{{ popular.cover_photo }}">
        </div>
        <div class="text-center">
            <div class="inline-block text-sm lg:text-sm text-gray-500 mb-4 sm:mb-8 border-b-2">
                {{ popular.category }}
            </div>
        </div>

        <div class="text-lg md:text-2xl lg:text-xl font-bold mb-2 text-center">
            {{ popular.title }}
        </div>
        <div class="text-sm md:text-base font-normal text-gray-600 mb-4 text-center">
            {{ popular.sub_title }}
        </div>
    </a>
</div>

templates/mixins/curriculum_card_5_travel.html
<div class="w-full sm:w-1/5 mb-10 px-4">
    <a href="{% url 'curriculums:detail' travel.pk %}">
        <div class="w-full h-72 bg-cover bg-center mb-4 "
             style="background-image: url({{ travel.cover_photo }});">
        </div>
        <div class="text-center">
            <div class="inline-block text-sm text-gray-500 mb-8 border-b-2">
                {{ travel.category }}
            </div>
        </div>

        <div class="text-lg font-bold mb-3 text-center">
            {{ travel.title }}
        </div>
        <div class="text-sm font-normal text-gray-700 mb-4 text-center">
            {{ travel.sub_title }}
        </div>
    </a>
</div>