config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("curriculums/", include("curriculums.urls", namespace="curriculums")),
    path("users/", include("users.urls", namespace="users")),
    path("book_clubs/", include("book_clubs.urls", namespace="book_clubs")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt",
                                             content_type='text/plain')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from curriculums import views as curriculum_views

app_name = "core"

urlpatterns = [path("", curriculum_views.HomeView.as_view(), name="home")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("sigup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
]

users/models.py
import uuid
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.shortcuts import reverse


class User(AbstractUser):
    """ Custom User Model """

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"

    GENDER_CHOICES = (
        (GENDER_MALE, "남자"),
        (GENDER_FEMALE, "여자"),
    )

    name = models.CharField(max_length=10, null=True, blank=True)
    nickname = models.CharField(max_length=10, null=True, blank=True)
    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=10, null=True, blank=True
    )
    birthdate = models.DateField(null=True, blank=True)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify Airbnb Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()
        return

    def avatar_photo(self):
        avatar = self.avatar.url
        return avatar

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("비밀번호가 틀렸습니다"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("존재하지 않는 아이디입니다"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("email", "name", "nickname",)

    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
from django.views.generic import FormView, DetailView
from django.urls import reverse_lazy
from django.shortcuts import redirect, reverse
from django.contrib.auth import authenticate, login, logout
from . import forms, models
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from . import forms, models, mixins
from django.contrib import messages


class LoginView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["email"].widget.attrs = {"placeholder": "아이디(이메일)"}
        form.fields["password"].widget.attrs = {"placeholder": "비밀번호"}
        return form

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["email"].widget.attrs = {"placeholder": "아이디(이메일)"}
        form.fields["password"].widget.attrs = {"placeholder": "비밀번호"}
        form.fields["password1"].widget.attrs = {"placeholder": "비밀번호 확인"}
        form.fields["name"].widget.attrs = {"placeholder": "이름"}
        form.fields["nickname"].widget.attrs = {"placeholder": "별명"}
        return form


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # to do: add succes message
    except models.User.DoesNotExist:
        # to do: add error message
        pass
    return redirect(reverse("core:home"))


class UserProfileView(DetailView):
    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "name",
        "nickname",
        "gender",
    )
    success_message = "Profile Updated"

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["name"].widget.attrs = {"placeholder": "이름"}
        form.fields["nickname"].widget.attrs = {"placeholder": "별명"}
        form.fields["gender"].widget.attrs = {"placeholder": "성별"}
        return form


class UpdatePasswordView(
    mixins.EmailLoginOnlyView,
    mixins.LoggedInOnlyView,
    SuccessMessageMixin,
    PasswordChangeView,
):
    template_name = "users/update-password.html"
    success_message = "Password Updated"

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["old_password"].widget.attrs = {"placeholder": "현재 비밀번호"}
        form.fields["new_password1"].widget.attrs = {"placeholder": "새로운 비밀번호"}
        form.fields["new_password2"].widget.attrs = {
            "placeholder": "새로운 비밀번호 확인"
        }
        return form

    def get_success_url(self):
        return self.request.user.get_absolute_url()

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
    Log In
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center  p-6 border-gray-400 mt-20">

        {% include 'mixins/auth/auth_form.html' with form=form cta="로그인" %}

        <div class="mt-5">
            <a href="{% url 'users:signup' %}" class="text-black font-medium text-sm">회원가입</a>
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center  p-6 border-gray-400 mt-20">

        {% include 'mixins/auth/auth_form.html' with form=form cta="회원가입 완료" %}

        <div class="mt-5">
            <span class="mr-2">이미 아이디가 있으신가요?</span>
            <a href="{% url 'users:login' %}" class="text-gray-800 border-b border-black font-medium">로그인</a>
        </div>

    </div>
{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="min-h-75vh">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
            {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}
        </div>
    </div>
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mt-20 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/auth/auth_form.html' with form=form cta="프로필 수정 완료" %}

        <div class="mt-5">
            <a href="{% url 'users:password' %}" class="text-gray-900 border-b border-black font-medium">비밀번호 변경</a>
        </div>

    </div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{ user_obj.name }}'s Profile
{% endblock page_title %}

{% block content %}

    <div class="min-h-50vh mt-24">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
            <div class="flex items-center">
                <span class="text-3xl mt-1">{{ user_obj.name }}</span>
            </div>
            <span class="text-lg mb-5">({{ user.nickname }})</span>
            {% if user == user_obj %}
                <a href="{% url 'users:update' %}" class="btn-link bg-gray-900">프로필 수정하기</a>
            {% endif %}
        </div>
        {% if user_obj.bookreviews.count > 0 %}
            <h3 class="mb-12 text-2xl text-center">{{ user_obj.name }}'s 서평</h3>
            <div class="container mx-auto pb-10 ">
                <div class="flex flex-wrap mb-10">
                    {% for bookreview in user_obj.bookreviews.all %}
                        {% include 'mixins/bookReview_card_user.html' with bookreview=bookreview %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}