book_clubs/urls.py
from django.urls import path

from . import views

app_name = "book_clubs"

urlpatterns = [
    path("", views.BookReviewView.as_view(), name="review"),
    path("<int:pk>", views.BookReviewDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditBookReviewView.as_view(), name="edit"),
    path("list/", views.BookClubListView.as_view(), name="home"),
    path("list/england", views.EnglandView.as_view(), name="england"),
    path("list/dog", views.DogView.as_view(), name="dog"),
    path("list/consumer", views.ConsumerView.as_view(), name="consumer"),
    path("list/think", views.ThinkView.as_view(), name="think"),
    path("create/", views.CreateBookReviewView.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("curriculums/", include("curriculums.urls", namespace="curriculums")),
    path("users/", include("users.urls", namespace="users")),
    path("book_clubs/", include("book_clubs.urls", namespace="book_clubs")),
    path("admin/", admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt",
                                             content_type='text/plain')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from curriculums import views as curriculum_views

app_name = "core"

urlpatterns = [path("", curriculum_views.HomeView.as_view(), name="home")]

book_clubs/models.py
from django.db import models
from core import models as core_models
from django.urls import reverse
from django_ckeditor_5.fields import CKEditor5Field
from ckeditor_uploader.fields import RichTextUploadingField


class AbstractItem_BookReview(core_models.TimeStampedModel):
    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Category_BookReview(AbstractItem_BookReview):
    class Meta:
        verbose_name_plural = "Categories_BookReview"
        ordering = ["name"]


class BookReview(core_models.TimeStampedModel):
    """ BookReview Model Definition """

    author = models.ForeignKey("users.User", related_name="bookreviews", on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    sub_title = models.CharField(max_length=50)
    category_BookReview = models.ForeignKey(
        "Category_BookReview",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="curriculums",
    )
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_clubs:detail", kwargs={"pk": self.pk})

book_clubs/forms.py
from django import forms
from . import models
from django_ckeditor_5.widgets import CKEditor5Widget
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django_ckeditor_5.fields import CKEditor5Field
from django_summernote.widgets import SummernoteWidget


class CreateBookReviewForm(forms.ModelForm):
    class Meta:
        model = models.BookReview
        fields = (
            "title",
            "sub_title",
            "category_BookReview",
            "description",
        )
        widgets = {
            'title': forms.TextInput(
                attrs={'placeholder': '제목을 입력하세요.'}
            ),
            'sub_title': forms.TextInput(
                attrs={'placeholder': '소제목을 입력하세요.'}
            ),
            'category_BookReview': forms.Select(
                attrs={'placeholder': '카테고리', 'class': 'custom-select'},
            ),
            'description': forms.Textarea(attrs={'placeholder': '내용을 입력하세요.'})
        }

    def save(self, *args, **kwargs):
        bookreview = super().save(commit=False)
        return bookreview

book_clubs/views.py
from django.views.generic import ListView, DetailView, TemplateView, FormView, UpdateView
from . import models, forms
from users import mixins as user_mixins
from django.http import Http404
from django.contrib import messages
from django.shortcuts import render, redirect, reverse


class BookReviewView(ListView):
    """ BookReviewView Definition """

    model = models.BookReview
    ordering = "-created"
    context_object_name = "BookReviews"  # object_list 이름 바꾸기
    template_name = "book_clubs/bookReview_list.html"


class BookReviewDetail(DetailView):
    """ BookReviewDetail Definition """

    model = models.BookReview
    context_object_name = "BookReviews"  # object_list 이름 바꾸기
    template_name = "book_clubs/bookReviewDetail.html"


class BookClubListView(TemplateView):
    template_name = "book_clubs/bookClub_list.html"


class EnglandView(ListView):
    model = models.BookReview
    ordering = "-created"
    context_object_name = "BookReviews"
    template_name = "book_clubs/bookClub_england.html"

    def get_context_data(self, **kwargs):
        context = super(EnglandView, self).get_context_data(**kwargs)
        context["englands"] = models.BookReview.objects.filter(category_BookReview="1").order_by("-created")
        return context


class DogView(ListView):
    model = models.BookReview
    ordering = "-created"
    context_object_name = "BookReviews"
    template_name = "book_clubs/bookClub_dog.html"

    def get_context_data(self, **kwargs):
        context = super(DogView, self).get_context_data(**kwargs)
        context["dogs"] = models.BookReview.objects.filter(category_BookReview="2").order_by("-created")
        return context


class ConsumerView(ListView):
    model = models.BookReview
    ordering = "-created"
    context_object_name = "BookReviews"
    template_name = "book_clubs/bookClub_consumer.html"

    def get_context_data(self, **kwargs):
        context = super(ConsumerView, self).get_context_data(**kwargs)
        context["consumers"] = models.BookReview.objects.filter(category_BookReview="3").order_by("-created")
        return context


class ThinkView(ListView):
    model = models.BookReview
    ordering = "-created"
    context_object_name = "BookReviews"
    template_name = "book_clubs/bookClub_think.html"

    def get_context_data(self, **kwargs):
        context = super(ThinkView, self).get_context_data(**kwargs)
        context["thinks"] = models.BookReview.objects.filter(category_BookReview="4").order_by("-created")
        return context


class EditBookReviewView(user_mixins.LoggedInOnlyView, UpdateView):
    model = models.BookReview
    template_name = "book_clubs/bookreview_edit.html"
    fields = (
        "title",
        "sub_title",
        "category_BookReview",
        "description",
    )

    def get_object(self, queryset=None):
        Bookreview = super().get_object(queryset=queryset)
        if Bookreview.author.pk != self.request.user.pk:
            raise Http404()
        return Bookreview


class CreateBookReviewView(user_mixins.LoggedInOnlyView, FormView):
    form_class = forms.CreateBookReviewForm
    template_name = "book_clubs/bookreview_create.html"

    def form_valid(self, form):
        BookReview = form.save()
        BookReview.author = self.request.user
        BookReview.save()
        form.save_m2m()
        messages.success(self.request, "서평 작성 완료")
        return redirect(reverse("book_clubs:detail", kwargs={"pk": BookReview.pk}))

templates/book_clubs/bookClub_consumer.html
{% extends "base.html" %}

{% block page_title %}
    커리북 | 내게 맞는 책, 지금 필요한 독서
{% endblock page_title %}

{% block content %}
    <div class="px-5">
        <div class="container mx-auto max-w-full pb-6 mt-20 text-center">
            <span class="font-extrabold text-lg mb-12 p-1">서평 - 소비자와 브랜드</span>
        </div>
        <div class="border-b border-black -mx-5"></div>
        <div class="container mx-auto max-w-full sm:max-w-full mt-10">
            <div class="flex-col sm:flex-row flex-wrap">
                {% for consumer in consumers %}
                    {% include 'mixins/bookReview_card_consumer.html' with consumer=consumer %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/book_clubs/bookClub_dog.html
{% extends "base.html" %}

{% block page_title %}
    커리북 | 내게 맞는 책, 지금 필요한 독서
{% endblock page_title %}

{% block content %}
    <div class="px-5">
        <div class="container mx-auto max-w-full pb-6 mt-20 text-center">
            <span class="font-extrabold text-lg mb-12 p-1">서평 - 대중화된 반려 교육의 오류</span>
        </div>
        <div class="border-b border-black -mx-5 mb-5"></div>
        <div class="container mx-auto max-w-full sm:max-w-full mt-5">
            <div class="flex-col sm:flex-row flex-wrap">
                {% for dog in dogs %}
                    {% include 'mixins/bookReview_card_dog.html' with dog=dog %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/book_clubs/bookClub_england.html
{% extends "base.html" %}

{% block page_title %}
    커리북 | 내게 맞는 책, 지금 필요한 독서
{% endblock page_title %}

{% block content %}
    <div class="px-5">
        <div class="container mx-auto max-w-full pb-6 mt-20 text-center">
            <span class="font-extrabold text-lg mb-12 p-1">서평 - 취향 여행법</span>
        </div>
        <div class="border-b border-black -mx-5"></div>
        <div class="container mx-auto max-w-full sm:max-w-full mt-10">
            <div class="flex-col sm:flex-row flex-wrap">
                {% for england in englands %}
                    {% include 'mixins/bookReview_card_england.html' with england=england %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/book_clubs/bookClub_list.html
{% extends "base.html" %}

{% block page_title %}
    커리북 | 취향 여행법 : 영국과 문화예술
{% endblock page_title %}

{% block content %}
    <div class="px-5">
        <div class="container mt-24 pb-6 text-center mx-auto xl:max-w-full">
            <span class="font-extrabold text-lg mb-12 p-1">진행중인 독서모임</span>
        </div>
        <div class="border-b border-black -mx-5
        ">
        </div>
    </div>
    <div class="flex flex-col sm:flex-row flex-wrap">
        <div class="w-full lg:w-1/3 mb-20 md:mb-24 px-3 md:px-16 lg:px-10 mt-10">
            <a href="{% url 'book_clubs:england' %}">
                <div class="w-auto h-auto bg-cover bg-center mb-4  ">
                    <img src="https://curribook-static.s3.ap-northeast-2.amazonaws.com/static/img/england.jpg">
                </div>
                <div class="text-center">
                    <div class="inline-block text-sm lg:text-sm text-gray-500 mb-4 sm:mb-8 border-b-2">
                        by 고아라
                    </div>
                </div>
                <div class="text-2xl md:text-3xl lg:text-2xl font-bold mb-2 text-center">
                    취향 여행법 : 영국과 문화예술
                </div>
                <div class="font-normal md:text-lg text-gray-600 mb-4 text-center">
                    진정한 여행은 외부가 아니라 내면의 환경이 바뀌어야 한다는 것
                </div>
            </a>
        </div>
        <div class="w-full lg:w-1/3 mb-20 md:mb-24 px-3 md:px-16 lg:px-10 mt-10">
            <a href="{% url 'book_clubs:dog' %}">
                <div class="w-auto h-auto bg-cover bg-center mb-4  ">
                    <img src="https://curribook-static.s3.ap-northeast-2.amazonaws.com/static/img/dog.jpg">
                </div>
                <div class="text-center">
                    <div class="inline-block text-sm lg:text-sm text-gray-500 mb-4 sm:mb-8 border-b-2">
                        by 김창조
                    </div>
                </div>
                <div class="text-2xl md:text-3xl lg:text-2xl font-bold mb-2 text-center">
                    대중화된 반려 교육의 오류
                </div>
                <div class="font-normal md:text-lg text-gray-600 mb-4 text-center">
                    반려견을 바라보는 우리의 눈높이는 어디쯤인가?
                </div>
            </a>
        </div>
        <div class="w-full lg:w-1/3 mb-20 md:mb-24 px-3 md:px-16 lg:px-10 mt-10">
            <a href="{% url 'book_clubs:consumer' %}">
                <div class="w-auto h-auto bg-cover bg-center mb-4  ">
                    <img src="https://curribook-static.s3.ap-northeast-2.amazonaws.com/static/img/consumer.jpg">
                </div>
                <div class="text-center">
                    <div class="inline-block text-sm lg:text-sm text-gray-500 mb-4 sm:mb-8 border-b-2">
                        by 김현우
                    </div>
                </div>
                <div class="text-2xl md:text-3xl lg:text-2xl font-bold mb-2 text-center">
                    소비자와 브랜드, 소유에서 존재를 향하다
                </div>
                <div class="font-normal md:text-lg text-gray-600 mb-4 text-center">
                    현대의 서비스들은 우리들의 소유와 존재 그사이에 아슬아슬하게 서 있다.
                </div>
            </a>
        </div>
        <div class="w-full lg:w-1/3 mb-20 md:mb-24 px-3 md:px-16 lg:px-10 mt-10">
            <a href="{% url 'book_clubs:think' %}">
                <div class="w-auto h-auto bg-cover bg-center mb-4  ">
                    <img src="https://curribook-static.s3.ap-northeast-2.amazonaws.com/static/img/think.jpg">
                </div>
                <div class="text-center">
                    <div class="inline-block text-sm lg:text-sm text-gray-500 mb-4 sm:mb-8 border-b-2">
                        by 박근혜
                    </div>
                </div>
                <div class="text-2xl md:text-3xl lg:text-2xl font-bold mb-2 text-center">
                    쉽게 접하는 인문학, 그 속에서 답을 찾다
                </div>
                <div class="font-normal md:text-lg text-gray-600 mb-4 text-center">
                    일상의 작은 고민거리부터 세상을 움직일 수 있는 큰 결정까지, 삶의 작고 큰 물음에 봉착했을 때 우리는 옛 지혜 속에서 그 답을 찾곤 합니다.
                </div>
            </a>
        </div>
    </div>


{% endblock content %}

templates/book_clubs/bookClub_think.html
{% extends "base.html" %}

{% block page_title %}
    커리북 | 내게 맞는 책, 지금 필요한 독서
{% endblock page_title %}

{% block content %}
    <div class="px-5">
        <div class="container mx-auto max-w-full pb-6 mt-20 text-center">
            <span class="font-extrabold text-lg mb-12 p-1">서평 - 쉽게 접하는 인문학</span>
        </div>
        <div class="border-b border-black -mx-5"></div>
        <div class="container mx-auto max-w-full sm:max-w-full mt-10">
            <div class="flex-col sm:flex-row flex-wrap">
                {% for think in thinks %}
                    {% include 'mixins/bookReview_card_think.html' with think=think %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/book_clubs/bookReviewDetail.html
{% extends "base.html" %}

{% block page_title %}
    {{ BookReviews.title }}
{% endblock page_title %}

{% block content %}
    <div class="container mx-auto flex-col justify-center px-4 md:px-10 lg:px-72">
        <div class="w-full">
            <div class="flex text-center justify-center pt-16">
                <div class="mt-12">
                    <div class="sub text-gray-600 text font-bold mb-1">{{ BookReviews.sub_title }}</div>
                    <h3 class="text-black text-2xl font-bold mb-3">{{ BookReviews.title }}</h3>

                </div>
            </div>
            <div class="mt-14 mb-8">
                {{ BookReviews.description | safe | linebreaks }}
            </div>
            <div class="w-1/3 mb-10 mx-auto">
                {% if BookReviews.author == user %}
                    <a href="{% url 'book_clubs:edit' BookReviews.pk %}" class="btn-link bg-gray-900 block">수정하기</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/book_clubs/bookReview_list.html
{% extends "base.html" %}

{% block page_title %}
    커리북 | 내게 맞는 책, 지금 필요한 독서
{% endblock page_title %}

{% block content %}
    <div class="px-5">
        <div class="container mx-auto max-w-full pb-6 mt-20 text-center">
            <span class="font-extrabold text-lg mb-12 border border-black p-1">전</span>
            <span class="font-extrabold text-lg mb-12 border-t border-r border-b border-black p-1 -mx-1">체</span>
        </div>
        <div class="border-b border-black -mx-5"></div>
        <div class="container mx-auto max-w-full sm:max-w-full mt-10">
            <div class="flex-col flex-wrap">
                {% for BookReviews in BookReviews %}
                    {% include 'mixins/bookReview_card.html' with BookReviews=BookReviews %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/book_clubs/bookreview_create.html
{% extends "base.html" %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mt-20 lg:w-5/12 md:w-1/2 xl:w-1/2 mx-auto my-10 flex flex-col items-center p-6">

        {% include 'mixins/bookreview/bookreview_form.html' with form=form cta="서평 작성 완료" %}

    </div>
{% endblock content %}

templates/book_clubs/bookreview_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mt-20 lg:w-5/12 md:w-1/2 xl:w-1/2 mx-auto my-10 flex flex-col items-center p-6">

        {% include 'mixins/bookreview/bookreview_form.html' with form=form cta="수정 완료" %}

    </div>
{% endblock content %}